name: Build CRAN-style R Documentation

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches: [main, master]

jobs:
  build_cran_docs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Needed to upload the artifact
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("roxygen2", "knitr", "rmarkdown", "devtools",
                                         "stats", "graphics", "plot3D", "ggplot2",
                                         "reshape2", "grid", "ggthemes", "tidyr",
                                         "statebins", "ggrepel", "RColorBrewer", "scales"))'

      - name: Generate documentation
        run: |
          Rscript -e 'devtools::document()'
          Rscript -e 'roxygen2::roxygenise()'
          Rscript -e 'devtools::build_manual(path = ".")'


      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cran-docs
          path: ./*.pdf 